name: sabian_tools
description: Sabian Tools Library
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  #Sprintf
  sprintf: ^7.0.0


  #Spinners
  flutter_spinkit: ^5.2.0

  #Font Awesome
  font_awesome_flutter: ^10.5.0

  #Cached images
  cached_network_image: ^3.2.3

  #Easy isolates
  easy_isolate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/RobotoCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/RobotoCondensed-BoldItalic.ttf
          style: italic
          weight: 700
