name: Sabian Tools Test
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'

      - name: Retrieve all packages
        run: flutter pub get

      - name: Run all unit tests
        run: flutter test